In [1]:
import os
d='.'
y = [filter(lambda x: os.path.isdir(os.path.join(d, x)), os.listdir(d))]

In [2]:
d = './train/'

alldir = [os.path.join(d, o) for o in os.listdir(d) 
                    if os.path.isdir(os.path.join(d,o))]

In [3]:
#print(alldir)

In [4]:
allfiles = []
for mypath in alldir:
    curfiles = [os.path.join(mypath, f) for f in os.listdir(mypath) if os.path.isfile(os.path.join(mypath, f))]
    allfiles.extend(curfiles)


In [5]:
#print(allfiles)

In [6]:
import xml.etree.ElementTree as ET
from lxml import etree
import itertools
#!pip install xmltodict

In [7]:
from bert_embedding import BertEmbedding
import pandas as pd
import numpy as np
import mxnet as mx
import pickle

/home/mounika/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [8]:
ctx = mx.gpu(0)
bert = BertEmbedding(ctx=ctx)

/home/mounika/anaconda3/lib/python3.6/site-packages/gluonnlp/model/block.py:113: UserWarning: `erf` operator support is not found. Please consider upgrading to mxnet >= 1.4
  warnings.warn('`erf` operator support is not found. '


In [9]:
def label_polarity(rating):
    if rating == 3.0:
        return 'neutral'
    elif rating > 3.0:
        return 'positive'
    else:
        return 'negative'

In [22]:
def label_polarity_num(rating):
    if rating == 3.0:
        return 1
    elif rating > 3.0:
        return 2
    else:
        return 0

In [23]:
utf8_parser = etree.XMLParser(encoding='utf-8', recover=True)
x_features = []
y = []
with open("./train/Reviews_Task2.txt",'w',encoding = 'utf-8') as ftext, open("./train/polarity.txt",'w',encoding = 'utf-8') as flabel:
    for eachfile in allfiles:
        with open(eachfile) as f:
            print(eachfile)
            it = itertools.chain('<root>',f,'</root>')
            root = ET.fromstringlist(it,parser=utf8_parser)
            for child in root:
                if child.tag in 'STARS':
                    flabel.write(label_polarity(float(child.text))+'\n')
                    y.append(label_polarity_num(float(child.text)))
                if child.tag in 'REVIEW':
                    #print(len(child.text))
                    ftext.write(str(child.text).strip().strip('\n')+'\n\n')
                    result = bert.embedding([child.text])
                    #print("length",len(result))
                    for i in np.arange(len(result)):
                        x_features.append(result[i][0])
            
x_features = np.array(x_features)
print("features shape",x_features.shape)
np.save('bert_sample_features',x_features)

./train/Ironic/2_11_RTS6EANBJF8O0.xml
./train/Ironic/15_5_R3UPN0Y95FJ8E.xml
./train/Ironic/14_17_R1T1APOY22KKN6.xml
./train/Ironic/8_8_R1UADG0E4JLKCE.xml
./train/Ironic/17_16_R2PAF0GF1PT0RH.xml
./train/Ironic/19_11_RCH4DJ0H38CV8.xml
./train/Ironic/27_14_R2FHC3NHL0T8UJ.xml
./train/Ironic/15_10_R2LI7PF47BH0HF.xml
./train/Ironic/16_4_R2Z5QF7Y4LHPEO.xml
./train/Ironic/20_12_R2GLNH1U43940X.xml
./train/Ironic/20_13_R3K82ZOBEZOH7W.xml
./train/Ironic/27_12_RTBDV3D382IYW.xml
./train/Ironic/29_18_R1WLZAH4TAPM55.xml
./train/Ironic/17_5_RFH3UT9TNAAAB.xml
./train/Ironic/1_1_R280644F3NWFFN.xml
./train/Ironic/9_8_RWAJWNKPNZZJ9.xml
./train/Ironic/32_9_R7C2P79OILQD8.xml
./train/Ironic/1_6_R3GAKPYR63VAW2.xml
./train/Ironic/8_12_R1FUPYGHYAG76B.xml
./train/Ironic/15_17_R6NYH235LG14C.xml
./train/Ironic/18_3_R1KR0XX13PKBEY.xml
./train/Ironic/25_5_R27YOGCKS5U023.xml
./train/Ironic/3_18_R13D2BDLFVJFBQ.xml
./train/Ironic/19_9_R1NAPC7VHZ8SVJ.xml
./train/Ironic/21_12_R3Q5VKRJUVE8EB.xml
./train/Ironic/30_6_RL8C44

./train/Ironic/16_16_R1G3PE5U7IONXK.xml
./train/Ironic/22_12_R1VQSBUHBG90R1.xml
./train/Ironic/28_3_R341CN15R9VX4Q.xml
./train/Ironic/27_4_RWSQIFTHNZCM7.xml
./train/Ironic/17_8_R35P87G7S1YZYP.xml
./train/Ironic/10_6_R222OQ5HMG8IW6.xml
./train/Ironic/31_4_R1LWA1AXUZGOXP.xml
./train/Ironic/3_4_REBAMEZU2XO9B.xml
./train/Ironic/15_9_R2DF1STG5QDJPG.xml
./train/Ironic/5_9_RHL5APZ9MEFD2.xml
./train/Ironic/14_6_R29BIVGI18POGZ.xml
./train/Ironic/17_1_R2NR6PNN0JXMRI.xml
./train/Ironic/28_4_R3U7JCSNGXTU3R.xml
./train/Ironic/14_5_R2334YRUI2S8D1.xml
./train/Ironic/11_6_R29F9YPMNXJFDQ.xml
./train/Ironic/12_15_R1PJXC9IGJ1SGH.xml
./train/Ironic/21_18_R1PH6TKNWE91QA.xml
./train/Ironic/16_1_RIU4P618YCDYU.xml
./train/Ironic/24_5_R1XDMNRFJMN45Y.xml
./train/Ironic/25_2_R1YDDX28V2RGFS.xml
./train/Ironic/12_7_R1P37H5L0NVOAN.xml
./train/Ironic/15_15_R2P5ZKHROB75H1.xml
./train/Ironic/7_13_R2U4RBEO13YGNU.xml
./train/Ironic/23_2_R418BR8JCQDL5.xml
./train/Ironic/5_12_RAXJO3OXS1FP5.xml
./train/Ironic/6_11_R3U5QR00

./train/Regular/19_16_R3H74C13TXU727.xml
./train/Regular/27_4_R3G2L5J76XJYMD.xml
./train/Regular/36_11_R2C2UY01XY52S.xml
./train/Regular/28_13_R3O2B4Q9CUTE8J.xml
./train/Regular/30_1_R2RCCMEBNA744P.xml
./train/Regular/35_8_R16DNO7RN9UUKR.xml
./train/Regular/23_7_R2SEOK484HC2FV.xml
./train/Regular/24_7_R2M0DU8KPKRYNP.xml
./train/Regular/34_9_R3QCKV6N8B5UZP.xml
./train/Regular/28_11_R17MORN6LHRZQZ.xml
./train/Regular/16_1_RU2IOVKQVJF1H.xml
./train/Regular/4_3_R3UUMPXH01HX4M.xml
./train/Regular/30_10_R342I8FQPZF0Z4.xml
./train/Regular/31_5_R33WTZFA5EPSED.xml
./train/Regular/11_16_R1YS6WDAD725AO.xml
./train/Regular/19_10_R1RZ8GC06C7PS1.xml
./train/Regular/22_1_R2X17F05SYYGS.xml
./train/Regular/19_4_R17XGO9DD9K9UQ.xml
./train/Regular/11_13_R37U1HO6SG9UHV.xml
./train/Regular/23_19_R56HY4465PPC0.xml
./train/Regular/15_10_R24Y0Y26SHSMWO.xml
./train/Regular/20_4_RBQVNB3B7UK15.xml
./train/Regular/4_14_R1EJS9Y17TR72G.xml
./train/Regular/7_6_R5YA6HVCMI8VW.xml
./train/Regular/2_2_R2IXN7ZDFT2MLE.xml

./train/Regular/26_15_R1RKISQBORWN6K.xml
./train/Regular/22_2_R1J2J9FBOULFV4.xml
./train/Regular/19_6_R2FVWVQ0FZPOHZ.xml
./train/Regular/29_18_R231EZFYZBNOG5.xml
./train/Regular/25_9_R2VPCGEWIH249C.xml
./train/Regular/17_18_R1HR9M0SMXE9WA.xml
./train/Regular/25_8_R2L41FR3YCL368.xml
./train/Regular/20_16_RWD8I8HYX4L7A.xml
./train/Regular/16_10_R1VKVR1DKNJP7H.xml
./train/Regular/1_16_R2VJTB1Y0JMYX2.xml
./train/Regular/16_3_RZYHUEM3T7Q0Y.xml
./train/Regular/14_8_R404A7I0PK5TX.xml
./train/Regular/5_11_R4X3HWF48PTE6.xml
./train/Regular/31_18_R1WDG23HDMX81W.xml
./train/Regular/21_6_R33VLVL5IBLXE4.xml
./train/Regular/13_18_RZE5WDWSNQ65L.xml
./train/Regular/19_9_R23V2PXGZUNWJ0.xml
./train/Regular/22_16_R2B47C0U6UCZLW.xml
./train/Regular/17_14_R2FN8TQEHTZHPZ.xml
./train/Regular/2_5_R89J4G2H6U8YP.xml
./train/Regular/3_18_R1AGD23MLG2404.xml
./train/Regular/2_3_RPVF83RK1ZUL3.xml
./train/Regular/12_16_R3PUVLAQNCCCGP.xml
./train/Regular/36_5_R2B6TTTKEHTZL7.xml
./train/Regular/6_8_R3L1WK2Q10GBTN.xml


In [24]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train,x_test,y_train,y_test = train_test_split(x_features,y,test_size=0.2,random_state=47)

In [25]:
import lightgbm as lgb

In [26]:
lgb_model = lgb.LGBMClassifier()
lgb_model.fit(x_train,y_train)
y_pred = lgb_model.predict(x_test)

/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [27]:
# to save model
filename = 'Task_2_model'
pickle.dump(lgb_model, open(filename, 'wb'))

In [28]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.45      0.20      0.28        45
          1       0.00      0.00      0.00         7
          2       0.69      0.90      0.78       108

avg / total       0.59      0.66      0.61       160

[[ 9  0 36]
 [ 0  0  7]
 [11  0 97]]


/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [29]:
print(cross_val_score(lgb_model,x_features,y,cv=5))

/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array 

[0.69135802 0.65625    0.71875    0.67924528 0.67295597]


/home/mounika/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
